# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: nucleos-form-extensions
  description: ⚙️ This library adds some custom form elements and validation for symfony.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, library, symfony, symfony-bridge, form, validation
